project: blocks_world
group: jdm
name: jdm_dit_blocks_world_15_v2
seed: 0

# General Parameters
mode: inference  # train or inference
enable_wandb : false
device: cuda:1
discount: 0.99
batch_size: 32
max_train_steps: 200000
save_interval: 50000
log_interval: 100

# Training Parameters
lr_hl: 1e-4
lr_ll: 1e-4
weight_decay: 1e-6
grad_clip_norm: 1.0
ema_rate: 0.999
hl_weight: 1.0
ll_weight: 1.0
hl_action_loss_weight: 2.0
ll_action_loss_weight: 2.0
# For previous t calculation
expected_sample_steps : 50

# Model Parameters
nn: dit
model_dim: 128
n_heads_HL: 10
n_heads_LL: 10
depth_HL: 8
depth_LL: 8
noise_schedule: cosine
predict_noise: false

# Sampling Parameters
solver: ddpm
sampling_steps: 50
use_ema: true
temperature: 1.0
w_cfg_hl: 0.5  # Classifier-free guidance weight for HL
w_cfg_ll: 0.5  # Classifier-free guidance weight for LL
preserve_history: true

# Evaluation Parameters
ckpt: 200000  # Checkpoint to load, null for final model
eval_batch_size: 16
eval_num_batches: 10
num_samples_per_inference: 1
hl_success_threshold: 0.1
ll_success_threshold: 0.1
save_samples: true
num_vis_batches: 2
max_vis_samples_per_batch: 2

task:
  env_name: blocks_world
  data_path: "dev/blocksworld/tamp_train_dataset.json"
  val_data_path: "dev/blocksworld/tamp_train_dataset.json"
  tokenizer_save_path: "dev/blocksworld/blocks_tokenizer"
  horizon: 8  # Number of high-level actions
  steps_per_action: 6  # Number of motion steps per action
  max_predicates: 11
  max_blocks: 5
  bit_dim: 6
  motion_dim: 3
  dim_mult_hl: [1, 2, 4]
  dim_mult_ll: [1, 2, 4]